import React from 'react';
import { MuiThemeProvider, createMuiTheme } from 'material-ui/styles';
import purple from 'material-ui/colors/purple';
import green from 'material-ui/colors/green';
import red from 'material-ui/colors/red';
import Button from 'material-ui/Button';

const theme = createMuiTheme({
  palette: {
    primary: red, // Purple and green play nicely together.
    secondary: {
      ...green,
      A400: '#00e677',
    },
    error: red,
  },
});

export default ({ children }) => (
  <MuiThemeProvider theme={theme}>{children}</MuiThemeProvider>
);

/* Palette generated by Material Palette - materialpalette.com/red/blue-grey */

// .dark-primary-color    { background: #D32F2F; }
// .default-primary-color { background: #F44336; }
// .light-primary-color   { background: #FFCDD2; }
// .text-primary-color    { color: #FFFFFF; }
// .accent-color          { background: #607D8B; }
// .primary-text-color    { color: #212121; }
// .secondary-text-color  { color: #757575; }
// .divider-color         { border-color: #BDBDBD; }
